"""Emit compact codepoint tables so the checker needs no third-party regex engine.

Two tables, because base letters and combining marks need different rules:

  SCRIPT_RANGES  base letters (category L*) -> script name.
  MARK_SCRIPTS   combining marks (category M*) -> the scripts the mark is
                 actually used with, from Unicode's Script_Extensions property.
                 A mark is legitimate on any base whose script is in that set,
                 which is why a combining macron is fine over Latin and an
                 Arabic fatha is not.
"""
import sys
import unicodedata

import regex

SCRIPTS = ['Latin', 'Arabic', 'Cyrillic', 'Greek', 'Han', 'Hiragana', 'Katakana',
           'Hangul', 'Thaana', 'Ethiopic', 'Bengali', 'Tamil', 'Malayalam',
           'Devanagari', 'Thai', 'Hebrew', 'Syriac', 'Armenian', 'Georgian',
           'Sinhala', 'Telugu', 'Kannada', 'Gujarati', 'Gurmukhi', 'Oriya',
           'Myanmar', 'Khmer', 'Lao', 'Tibetan', 'Mongolian', 'Cherokee', 'Coptic']

LIMIT = 0x30000

SCRIPT_PATS = {s: regex.compile(r'\p{Script=%s}' % s) for s in SCRIPTS}
SCX_PATS = {s: regex.compile(r'\p{scx=%s}' % s) for s in SCRIPTS}
COMMON = regex.compile(r'\p{Script=Common}')
INHERITED = regex.compile(r'\p{Script=Inherited}')


def collapse(pairs):
    """[(cp, value)] -> [(lo, hi, value)] merging runs that share a value."""
    out = []
    for cp, val in pairs:
        if out and out[-1][2] == val and out[-1][1] == cp - 1:
            out[-1][1] = cp
        else:
            out.append([cp, cp, val])
    return out


base, marks, neutral = [], [], []
for cp in range(LIMIT):
    ch = chr(cp)
    cat = unicodedata.category(ch)
    if cat.startswith('L'):
        for s in SCRIPTS:
            if SCRIPT_PATS[s].match(ch):
                base.append((cp, s))
                break
        else:
            # Letters with Script=Common or Inherited belong to no single script
            # and are legitimate anywhere: the Japanese prolonged sound mark,
            # Arabic tatweel, the modifier half-ring used for 'ayn in English
            # transliteration. Neutral, exactly like punctuation.
            if COMMON.match(ch) or INHERITED.match(ch):
                neutral.append((cp, 'neutral'))
    elif cat.startswith('M'):
        allowed = tuple(s for s in SCRIPTS if SCX_PATS[s].match(ch))
        if allowed:
            marks.append((cp, allowed))

print('# Generated by tools/genranges.py -- do not edit by hand.')
print('#')
print('# SCRIPT_RANGES maps base letters (Unicode category L*) to their script.')
print('# Punctuation, digits, spaces and symbols are script-neutral and are')
print('# deliberately absent: every edition uses ASCII punctuation and Latin digits.')
print('#')
print('# MARK_SCRIPTS maps combining marks (category M*) to the scripts they are')
print('# actually used with (Script_Extensions). A mark on a base outside that set')
print('# is an anomaly -- an Arabic fatha inside a Dutch word, say.')
print()

print('SCRIPT_RANGES = {')
by_script = {}
for lo, hi, s in collapse(base):
    by_script.setdefault(s, []).append((lo, hi))
for s in SCRIPTS:
    if s in by_script:
        body = ', '.join('(0x%X, 0x%X)' % r for r in by_script[s])
        print('    %r: [%s],' % (s, body))
print('}')
print()

print('# Letters that belong to no single script (Script=Common or Inherited) and')
print('# are therefore legitimate in any edition.')
print('NEUTRAL_LETTERS = [')
for lo, hi, _ in collapse(neutral):
    print('    (0x%X, 0x%X),' % (lo, hi))
print(']')
print()

print('MARK_SCRIPTS = [')
for lo, hi, allowed in collapse(marks):
    print('    (0x%X, 0x%X, %r),' % (lo, hi, allowed))
print(']')

print('base ranges: %d  mark ranges: %d' % (
    sum(len(v) for v in by_script.values()), len(collapse(marks))), file=sys.stderr)
